"""Change kontaktId to beaconId and lastEventTimestamp to lastSeen

Revision ID: 7650353b13df
Revises: e0d7ac5bc693
Create Date: 2020-10-26 10:36:01.553936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7650353b13df'
down_revision = 'e0d7ac5bc693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('beaconId', sa.String(), nullable=True))
    op.add_column('items', sa.Column('lastSeen', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_items_beaconId'), 'items', ['beaconId'], unique=False)
    op.create_index(op.f('ix_items_lastSeen'), 'items', ['lastSeen'], unique=False)
    op.drop_index('ix_items_kontaktId', table_name='items')
    op.drop_index('ix_items_lastEventTimestamp', table_name='items')
    op.drop_column('items', 'lastEventTimestamp')
    op.drop_column('items', 'kontaktId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('kontaktId', sa.VARCHAR(), nullable=True))
    op.add_column('items', sa.Column('lastEventTimestamp', sa.DATETIME(), nullable=True))
    op.create_index('ix_items_lastEventTimestamp', 'items', ['lastEventTimestamp'], unique=False)
    op.create_index('ix_items_kontaktId', 'items', ['kontaktId'], unique=False)
    op.drop_index(op.f('ix_items_lastSeen'), table_name='items')
    op.drop_index(op.f('ix_items_beaconId'), table_name='items')
    op.drop_column('items', 'lastSeen')
    op.drop_column('items', 'beaconId')
    # ### end Alembic commands ###
