"""Test migration

Revision ID: 90fde3e42e28
Revises: e7209ec63004
Create Date: 2020-10-24 23:48:35.121351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90fde3e42e28'
down_revision = 'e7209ec63004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
