"""empty message

Revision ID: 9dc90db3cd99
Revises: cde1ae0c4961
Create Date: 2020-10-24 23:44:42.581510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc90db3cd99'
down_revision = 'cde1ae0c4961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
