"""empty message

Revision ID: cde1ae0c4961
Revises: 
Create Date: 2020-10-24 23:40:31.402018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde1ae0c4961'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kontaktIdToType_kontaktId', table_name='kontaktIdToType')
    op.drop_index('ix_kontaktIdToType_type', table_name='kontaktIdToType')
    op.drop_table('kontaktIdToType')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kontaktIdToType',
    sa.Column('kontaktId', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('kontaktId')
    )
    op.create_index('ix_kontaktIdToType_type', 'kontaktIdToType', ['type'], unique=False)
    op.create_index('ix_kontaktIdToType_kontaktId', 'kontaktIdToType', ['kontaktId'], unique=False)
    # ### end Alembic commands ###
