"""empty message

Revision ID: e7209ec63004
Revises: 9dc90db3cd99
Create Date: 2020-10-24 23:45:59.491116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7209ec63004'
down_revision = '9dc90db3cd99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
